name: video-processing-b
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch
  - pytorch-cuda=12.4
  - torchvision
  - torchaudio
  - numpy
  - tqdm
  - loguru
  - scikit-image
  - scikit-learn
  - pillow
  - h5py
  - matplotlib
  - scipy
  - pyyaml
  - fastapi>=0.68.0
  - uvicorn>=0.15.0
  - pydantic>=1.8.0
  - python-multipart>=0.0.5
  - pip
  - pip:
    - opencv-python
    - opencv-contrib-python
    - thop
    - ninja
    - tabulate
    - tensorboard
    - lap
    - motmetrics
    - filterpy
    - prettytable
    - easydict
    - yacs
    - termcolor
    - gdown
    - onnx
    - onnxruntime-gpu
    - tensorboardX
    - seaborn
    - nvidia-ml-py3
    - cython_bbox
    - -e ./vendor/BoTSORT
    - -e ./vendor/rtmlib
    - -e ./vendor/ResGCNv1